version: "3.7"

networks:
  backend:
    driver: bridge
    external: true

services:
  traefik:
    image: traefik:v2.4
    networks:
      - backend
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.traefik.address=:8080
      - traefik.docker.network=backend
    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: mongo:4.4
    container_name: fumongo
    command: mongod
    networks:
      - backend
    ports:
      - "27018:27017"
    volumes:
      - "./data/mongo:/data/db"
      - "/data/mongo-entrypoint/:/docker-entrypoint-initdb.d/"

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /server
    networks:
      - backend
    volumes:
      - .:/server
    depends_on:
      - database
    entrypoint: go run main.go
    environment:
      - MONGO_URL="database:27017"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=server
      - traefik.http.routers.server.rule=Host(`app.docker.localhost`)
      - traefik.http.services.server.loadbalancer.server.port=80
      - traefik.http.routers.server.entrypoints=web
      - traefik.docker.network=backend


